const districts = [
    {"city": "Cần Thơ", "district": "Bình Thủy"},
    {"city": "Cần Thơ", "district": "Cái Răng"},
    {"city": "Cần Thơ", "district": "Cờ Đỏ"},
    {"city": "Cần Thơ", "district": "Ninh Kiều"},
    {"city": "Cần Thơ", "district": "Ô Môn"},
    {"city": "Cần Thơ", "district": "Phong Điền"},
    {"city": "Cần Thơ", "district": "Thới Lai"},
    {"city": "Cần Thơ", "district": "Thốt Nốt"},
    {"city": "Cần Thơ", "district": "Vĩnh Thạnh"},
    {"city": "Đà Nẵng", "district": "Cẩm Lệ"},
    {"city": "Đà Nẵng", "district": "Hải Châu"},
    {"city": "Đà Nẵng", "district": "Hòa Vang"},
    {"city": "Đà Nẵng", "district": "Liên Chiểu"},
    {"city": "Đà Nẵng", "district": "Ngũ Hành Sơn"},
    {"city": "Đà Nẵng", "district": "Sơn Trà"},
    {"city": "Đà Nẵng", "district": "Thanh Khê"},
    {"city": "Hải Phòng", "district": "An Dương"},
    {"city": "Hải Phòng", "district": "An Lão"},
    {"city": "Hải Phòng", "district": "Bạch Long Vĩ"},
    {"city": "Hải Phòng", "district": "Cát Hải"},
    {"city": "Hải Phòng", "district": "Đồ Sơn"},
    {"city": "Hải Phòng", "district": "Dương Kinh"},
    {"city": "Hải Phòng", "district": "Hải An"},
    {"city": "Hải Phòng", "district": "Hồng Bàng"},
    {"city": "Hải Phòng", "district": "Kiến An"},
    {"city": "Hải Phòng", "district": "Kiến Thụy"},
    {"city": "Hải Phòng", "district": "Lê Chân"},
    {"city": "Hải Phòng", "district": "Ngô Quyền"},
    {"city": "Hải Phòng", "district": "Thủy Nguyên"},
    {"city": "Hải Phòng", "district": "Tiên Lãng"},
    {"city": "Hải Phòng", "district": "Vĩnh Bảo"},
    {"city": "Hà Nội", "district": "Bắc Từ Liêm"},
    {"city": "Hà Nội", "district": "Ba Đình"},
    {"city": "Hà Nội", "district": "Ba Vì"},
    {"city": "Hà Nội", "district": "Cầu Giấy"},
    {"city": "Hà Nội", "district": "Chương Mỹ"},
    {"city": "Hà Nội", "district": "Đan Phượng"},
    {"city": "Hà Nội", "district": "Đông Anh"},
    {"city": "Hà Nội", "district": "Đống Đa"},
    {"city": "Hà Nội", "district": "Gia Lâm"},
    {"city": "Hà Nội", "district": "Hà Đông"},
    {"city": "Hà Nội", "district": "Hai Bà Trưng"},
    {"city": "Hà Nội", "district": "Hoài Đức"},
    {"city": "Hà Nội", "district": "Hoàng Mai"},
    {"city": "Hà Nội", "district": "Hoàn Kiếm"},
    {"city": "Hà Nội", "district": "Long Biên"},
    {"city": "Hà Nội", "district": "Mê Linh"},
    {"city": "Hà Nội", "district": "Mỹ Đức"},
    {"city": "Hà Nội", "district": "Nam Từ Liêm"},
    {"city": "Hà Nội", "district": "Phúc Thọ"},
    {"city": "Hà Nội", "district": "Phú Xuyên"},
    {"city": "Hà Nội", "district": "Quốc Oai"},
    {"city": "Hà Nội", "district": "Sóc Sơn"},
    {"city": "Hà Nội", "district": "Tây Hồ"},
    {"city": "Hà Nội", "district": "Thạch Thất"},
    {"city": "Hà Nội", "district": "Thanh Oai"},
    {"city": "Hà Nội", "district": "Thanh Trì"},
    {"city": "Hà Nội", "district": "Thanh Xuân"},
    {"city": "Hà Nội", "district": "Thường Tín"},
    {"city": "Hà Nội", "district": "Ứng Hòa"},
    {"city": "TP Hồ Chí Minh", "district": "Bình Chánh"},
    {"city": "TP Hồ Chí Minh", "district": "Bình Tân"},
    {"city": "TP Hồ Chí Minh", "district": "Bình Thạnh"},
    {"city": "TP Hồ Chí Minh", "district": "Cần Giờ"},
    {"city": "TP Hồ Chí Minh", "district": "Củ Chi"},
    {"city": "TP Hồ Chí Minh", "district": "Gò Vấp"},
    {"city": "TP Hồ Chí Minh", "district": "Hóc Môn"},
    {"city": "TP Hồ Chí Minh", "district": "Nhà Bè"},
    {"city": "TP Hồ Chí Minh", "district": "Phú Nhuận"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 1"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 2"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 3"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 4"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 5"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 6"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 7"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 8"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 9"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 10"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 11"},
    {"city": "TP Hồ Chí Minh", "district": "Quận 12"},
    {"city": "TP Hồ Chí Minh", "district": "Tân Bình"},
    {"city": "TP Hồ Chí Minh", "district": "Tân Phú"},
    {"city": "TP Hồ Chí Minh", "district": "Thủ Đức"},
    {"city": "An Giang", "district": "An Phú"},
    {"city": "An Giang", "district": "Châu Đốc"},
    {"city": "An Giang", "district": "Châu Phú"},
    {"city": "An Giang", "district": "Châu Thành"},
    {"city": "An Giang", "district": "Chợ Mới"},
    {"city": "An Giang", "district": "Long Xuyên"},
    {"city": "An Giang", "district": "Phú Tân"},
    {"city": "An Giang", "district": "Thoại Sơn"},
    {"city": "An Giang", "district": "Tịnh Biên"},
    {"city": "An Giang", "district": "Tri Tôn"},
    {"city": "Bà Rịa - Vũng Tàu", "district": "Bà Rịa"},
    {"city": "Bà Rịa - Vũng Tàu", "district": "Châu Đức"},
    {"city": "Bà Rịa - Vũng Tàu", "district": "Côn Đảo"},
    {"city": "Bà Rịa - Vũng Tàu", "district": "Đất Đỏ"},
    {"city": "Bà Rịa - Vũng Tàu", "district": "Long Điền"},
    {"city": "Bà Rịa - Vũng Tàu", "district": "Vũng Tàu"},
    {"city": "Bà Rịa - Vũng Tàu", "district": "Xuyên Mộc"},
    {"city": "Bắc Giang", "district": "Bắc Giang"},
    {"city": "Bắc Giang", "district": "Hiệp Hòa"},
    {"city": "Bắc Giang", "district": "Lạng Giang"},
    {"city": "Bắc Giang", "district": "Lục Nam"},
    {"city": "Bắc Giang", "district": "Lục Ngạn"},
    {"city": "Bắc Giang", "district": "Sơn Động"},
    {"city": "Bắc Giang", "district": "Tân Yên"},
    {"city": "Bắc Giang", "district": "Việt Yên"},
    {"city": "Bắc Giang", "district": "Yên Dũng"},
    {"city": "Bắc Giang", "district": "Yên Thế"},
    {"city": "Bắc Kạn", "district": "Ba Bể"},
    {"city": "Bắc Kạn", "district": "Bạch Thông"},
    {"city": "Bắc Kạn", "district": "Bắc Kạn"},
    {"city": "Bắc Kạn", "district": "Chợ Đồn"},
    {"city": "Bắc Kạn", "district": "Chợ Mới"},
    {"city": "Bắc Kạn", "district": "Na Rì"},
    {"city": "Bắc Kạn", "district": "Ngân Sơn"},
    {"city": "Bắc Kạn", "district": "Pác Nặm"},
    {"city": "Bạc Liêu", "district": "Bạc Liêu"},
    {"city": "Bạc Liêu", "district": "Đông Hải"},
    {"city": "Bạc Liêu", "district": "Hòa Bình"},
    {"city": "Bạc Liêu", "district": "Hồng Dân"},
    {"city": "Bạc Liêu", "district": "Phước Long"},
    {"city": "Bạc Liêu", "district": "Vĩnh Lợi"},
    {"city": "Bắc Ninh", "district": "Bắc Ninh"},
    {"city": "Bắc Ninh", "district": "Gia Bình"},
    {"city": "Bắc Ninh", "district": "Lương Tài"},
    {"city": "Bắc Ninh", "district": "Quế Võ"},
    {"city": "Bắc Ninh", "district": "Thuận Thành"},
    {"city": "Bắc Ninh", "district": "Tiên Du"},
    {"city": "Bắc Ninh", "district": "Yên Phong"},
    {"city": "Bến Tre", "district": "Ba Tri"},
    {"city": "Bến Tre", "district": "Bến Tre"},
    {"city": "Bến Tre", "district": "Bình Đại"},
    {"city": "Bến Tre", "district": "Châu Thành"},
    {"city": "Bến Tre", "district": "Chợ Lách"},
    {"city": "Bến Tre", "district": "Giồng Trôm"},
    {"city": "Bến Tre", "district": "Mỏ Cày Bắc"},
    {"city": "Bến Tre", "district": "Mỏ Cày Nam"},
    {"city": "Bến Tre", "district": "Thạnh Phú"},
    {"city": "Bình Định", "district": "An Lão"},
    {"city": "Bình Định", "district": "Hoài Ân"},
    {"city": "Bình Định", "district": "Hoài Nhơn"},
    {"city": "Bình Định", "district": "Phù Cát"},
    {"city": "Bình Định", "district": "Phù Mỹ"},
    {"city": "Bình Định", "district": "Quy Nhơn"},
    {"city": "Bình Định", "district": "Tây Sơn"},
    {"city": "Bình Định", "district": "Tuy Phước"},
    {"city": "Bình Định", "district": "Vân Canh"},
    {"city": "Bình Định", "district": "Vĩnh Thạnh"},
    {"city": "Bình Dương", "district": "Bắc Tân Uyên"},
    {"city": "Bình Dương", "district": "Bàu Bàng"},
    {"city": "Bình Dương", "district": "Dầu Tiếng"},
    {"city": "Bình Dương", "district": "Phú Giáo"},
    {"city": "Bình Dương", "district": "Thủ Dầu Một"},
    {"city": "Bình Phước", "district": "Bù Đăng"},
    {"city": "Bình Phước", "district": "Bù Đốp"},
    {"city": "Bình Phước", "district": "Bù Gia Mập"},
    {"city": "Bình Phước", "district": "Chơn Thành"},
    {"city": "Bình Phước", "district": "Đồng Phú"},
    {"city": "Bình Phước", "district": "Hớn Quản"},
    {"city": "Bình Phước", "district": "Lộc Ninh"},
    {"city": "Bình Phước", "district": "Phú Riềng"},
    {"city": "Bình Thuận", "district": "Bắc Bình"},
    {"city": "Bình Thuận", "district": "Đức Linh"},
    {"city": "Bình Thuận", "district": "Hàm Tân"},
    {"city": "Bình Thuận", "district": "Hàm Thuận Bắc"},
    {"city": "Bình Thuận", "district": "Hàm Thuận Nam"},
    {"city": "Bình Thuận", "district": "Phan Thiết"},
    {"city": "Bình Thuận", "district": "Phú Quý"},
    {"city": "Bình Thuận", "district": "Tánh Linh"},
    {"city": "Bình Thuận", "district": "Tuy Phong"},
    {"city": "Cà Mau", "district": "Cái Nước"},
    {"city": "Cà Mau", "district": "Cà Mau"},
    {"city": "Cà Mau", "district": "Đầm Dơi"},
    {"city": "Cà Mau", "district": "Năm Căn"},
    {"city": "Cà Mau", "district": "Ngọc Hiển"},
    {"city": "Cà Mau", "district": "Phú Tân"},
    {"city": "Cà Mau", "district": "Thới Bình"},
    {"city": "Cà Mau", "district": "Trần Văn Thời"},
    {"city": "Cà Mau", "district": "U Minh"},
    {"city": "Cao Bằng", "district": "Bảo Lạc"},
    {"city": "Cao Bằng", "district": "Bảo Lâm"},
    {"city": "Cao Bằng", "district": "Cao Bằng"},
    {"city": "Cao Bằng", "district": "Hạ Lang"},
    {"city": "Cao Bằng", "district": "Hà Quảng"},
    {"city": "Cao Bằng", "district": "Hòa An"},
    {"city": "Cao Bằng", "district": "Nguyên Bình"},
    {"city": "Cao Bằng", "district": "Phục Hòa"},
    {"city": "Cao Bằng", "district": "Quảng Uyên"},
    {"city": "Cao Bằng", "district": "Thạch An"},
    {"city": "Cao Bằng", "district": "Thông Nông"},
    {"city": "Cao Bằng", "district": "Trà Lĩnh"},
    {"city": "Cao Bằng", "district": "Trùng Khánh"},
    {"city": "Đắk Lắk", "district": "Buôn Đôn"},
    {"city": "Đắk Lắk", "district": "Buôn Ma Thuột"},
    {"city": "Đắk Lắk", "district": "Cư Kuin"},
    {"city": "Đắk Lắk", "district": "Cư M'gar"},
    {"city": "Đắk Lắk", "district": "Ea H'leo"},
    {"city": "Đắk Lắk", "district": "Ea Kar"},
    {"city": "Đắk Lắk", "district": "Ea Súp"},
    {"city": "Đắk Lắk", "district": "Krông Ana"},
    {"city": "Đắk Lắk", "district": "Krông Bông"},
    {"city": "Đắk Lắk", "district": "Krông Búk"},
    {"city": "Đắk Lắk", "district": "Krông Năng"},
    {"city": "Đắk Lắk", "district": "Krông Pắc (Krông Pắk)"},
    {"city": "Đắk Lắk", "district": "Lắk"},
    {"city": "Đắk Lắk", "district": "M'Drắk"},
    {"city": "Đắk Nông", "district": "Cư Jút"},
    {"city": "Đắk Nông", "district": "Đăk Glong"},
    {"city": "Đắk Nông", "district": "Đắk Mil"},
    {"city": "Đắk Nông", "district": "Đắk R'Lấp"},
    {"city": "Đắk Nông", "district": "Đắk Song"},
    {"city": "Đắk Nông", "district": "Krông Nô"},
    {"city": "Đắk Nông", "district": "Tuy Đức"},
    {"city": "Điện Biên", "district": "Điện Biên"},
    {"city": "Điện Biên", "district": "Điện Biên Đông"},
    {"city": "Điện Biên", "district": "Điện Biên Phủ"},
    {"city": "Điện Biên", "district": "Mường Ảng"},
    {"city": "Điện Biên", "district": "Mường Chà"},
    {"city": "Điện Biên", "district": "Mường Nhé"},
    {"city": "Điện Biên", "district": "Nậm Pồ"},
    {"city": "Điện Biên", "district": "Tủa Chùa"},
    {"city": "Điện Biên", "district": "Tuần Giáo"},
    {"city": "Đồng Nai", "district": "Biên Hòa"},
    {"city": "Đồng Nai", "district": "Cẩm Mỹ"},
    {"city": "Đồng Nai", "district": "Định Quán"},
    {"city": "Đồng Nai", "district": "Long Thành"},
    {"city": "Đồng Nai", "district": "Nhơn Trạch"},
    {"city": "Đồng Nai", "district": "Tân Phú"},
    {"city": "Đồng Nai", "district": "Thống Nhất"},
    {"city": "Đồng Nai", "district": "Trảng Bom"},
    {"city": "Đồng Nai", "district": "Vĩnh Cửu"},
    {"city": "Đồng Nai", "district": "Xuân Lộc"},
    {"city": "Đồng Tháp", "district": "Cao Lãnh"},
    {"city": "Đồng Tháp", "district": "Cao Lãnh (thành phố)"},
    {"city": "Đồng Tháp", "district": "Châu Thành"},
    {"city": "Đồng Tháp", "district": "Hồng Ngự"},
    {"city": "Đồng Tháp", "district": "Lai Vung"},
    {"city": "Đồng Tháp", "district": "Lấp Vò"},
    {"city": "Đồng Tháp", "district": "Sa Đéc"},
    {"city": "Đồng Tháp", "district": "Tam Nông"},
    {"city": "Đồng Tháp", "district": "Tân Hồng"},
    {"city": "Đồng Tháp", "district": "Thanh Bình"},
    {"city": "Đồng Tháp", "district": "Tháp Mười"},
    {"city": "Gia Lai", "district": "Chư Păh"},
    {"city": "Gia Lai", "district": "Chư Prông"},
    {"city": "Gia Lai", "district": "Chư Pưh"},
    {"city": "Gia Lai", "district": "Chư Sê"},
    {"city": "Gia Lai", "district": "Đắk Đoa"},
    {"city": "Gia Lai", "district": "Đak Pơ"},
    {"city": "Gia Lai", "district": "Đức Cơ"},
    {"city": "Gia Lai", "district": "Ia Grai"},
    {"city": "Gia Lai", "district": "Ia Pa"},
    {"city": "Gia Lai", "district": "K'Bang"},
    {"city": "Gia Lai", "district": "Kông Chro"},
    {"city": "Gia Lai", "district": "Krông Pa"},
    {"city": "Gia Lai", "district": "Mang Yang"},
    {"city": "Gia Lai", "district": "Phú Thiện"},
    {"city": "Gia Lai", "district": "Pleiku"},
    {"city": "Hà Giang", "district": "Bắc Mê"},
    {"city": "Hà Giang", "district": "Bắc Quang"},
    {"city": "Hà Giang", "district": "Đồng Văn"},
    {"city": "Hà Giang", "district": "Hà Giang"},
    {"city": "Hà Giang", "district": "Hoàng Su Phì"},
    {"city": "Hà Giang", "district": "Mèo Vạc"},
    {"city": "Hà Giang", "district": "Quản Bạ"},
    {"city": "Hà Giang", "district": "Quang Bình"},
    {"city": "Hà Giang", "district": "Vị Xuyên"},
    {"city": "Hà Giang", "district": "Xín Mần"},
    {"city": "Hà Giang", "district": "Yên Minh"},
    {"city": "Hà Nam", "district": "Bình Lục"},
    {"city": "Hà Nam", "district": "Duy Tiên"},
    {"city": "Hà Nam", "district": "Kim Bảng"},
    {"city": "Hà Nam", "district": "Lý Nhân"},
    {"city": "Hà Nam", "district": "Phủ Lý"},
    {"city": "Hà Nam", "district": "Thanh Liêm"},
    {"city": "Hà Tĩnh", "district": "Cẩm Xuyên"},
    {"city": "Hà Tĩnh", "district": "Can Lộc"},
    {"city": "Hà Tĩnh", "district": "Đức Thọ"},
    {"city": "Hà Tĩnh", "district": "Hà Tĩnh"},
    {"city": "Hà Tĩnh", "district": "Hương Khê"},
    {"city": "Hà Tĩnh", "district": "Hương Sơn"},
    {"city": "Hà Tĩnh", "district": "Kỳ Anh"},
    {"city": "Hà Tĩnh", "district": "Lộc Hà"},
    {"city": "Hà Tĩnh", "district": "Nghi Xuân"},
    {"city": "Hà Tĩnh", "district": "Thạch Hà"},
    {"city": "Hà Tĩnh", "district": "Vũ Quang"},
    {"city": "Hải Dương", "district": "Bình Giang"},
    {"city": "Hải Dương", "district": "Cẩm Giàng"},
    {"city": "Hải Dương", "district": "Gia Lộc"},
    {"city": "Hải Dương", "district": "Hải Dương"},
    {"city": "Hải Dương", "district": "Kim Thành"},
    {"city": "Hải Dương", "district": "Kinh Môn"},
    {"city": "Hải Dương", "district": "Nam Sách"},
    {"city": "Hải Dương", "district": "Ninh Giang"},
    {"city": "Hải Dương", "district": "Thanh Hà"},
    {"city": "Hải Dương", "district": "Thanh Miện"},
    {"city": "Hải Dương", "district": "Tứ Kỳ"},
    {"city": "Hậu Giang", "district": "Châu Thành"},
    {"city": "Hậu Giang", "district": "Châu Thành A"},
    {"city": "Hậu Giang", "district": "Long Mỹ"},
    {"city": "Hậu Giang", "district": "Phụng Hiệp"},
    {"city": "Hậu Giang", "district": "Vị Thanh"},
    {"city": "Hậu Giang", "district": "Vị Thủy"},
    {"city": "Hòa Bình", "district": "Cao Phong"},
    {"city": "Hòa Bình", "district": "Đà Bắc"},
    {"city": "Hòa Bình", "district": "Hòa Bình"},
    {"city": "Hòa Bình", "district": "Kim Bôi"},
    {"city": "Hòa Bình", "district": "Kỳ Sơn"},
    {"city": "Hòa Bình", "district": "Lạc Sơn"},
    {"city": "Hòa Bình", "district": "Lạc Thủy"},
    {"city": "Hòa Bình", "district": "Lương Sơn"},
    {"city": "Hòa Bình", "district": "Mai Châu"},
    {"city": "Hòa Bình", "district": "Tân Lạc"},
    {"city": "Hòa Bình", "district": "Yên Thủy"},
    {"city": "Hưng Yên", "district": "Ân Thi"},
    {"city": "Hưng Yên", "district": "Hưng Yên"},
    {"city": "Hưng Yên", "district": "Khoái Châu"},
    {"city": "Hưng Yên", "district": "Kim Động"},
    {"city": "Hưng Yên", "district": "Mỹ Hào"},
    {"city": "Hưng Yên", "district": "Phù Cừ"},
    {"city": "Hưng Yên", "district": "Tiên Lữ"},
    {"city": "Hưng Yên", "district": "Văn Giang"},
    {"city": "Hưng Yên", "district": "Văn Lâm"},
    {"city": "Hưng Yên", "district": "Yên Mỹ"},
    {"city": "Khánh Hòa", "district": "Cam Lâm"},
    {"city": "Khánh Hòa", "district": "Cam Ranh"},
    {"city": "Khánh Hòa", "district": "Diên Khánh"},
    {"city": "Khánh Hòa", "district": "Khánh Sơn"},
    {"city": "Khánh Hòa", "district": "Khánh Vĩnh"},
    {"city": "Khánh Hòa", "district": "Nha Trang"},
    {"city": "Khánh Hòa", "district": "Trường Sa [Spratly Islands]"},
    {"city": "Khánh Hòa", "district": "Vạn Ninh"},
    {"city": "Kiên Giang", "district": "An Biên"},
    {"city": "Kiên Giang", "district": "An Minh"},
    {"city": "Kiên Giang", "district": "Châu Thành"},
    {"city": "Kiên Giang", "district": "Giang Thành"},
    {"city": "Kiên Giang", "district": "Giồng Riềng"},
    {"city": "Kiên Giang", "district": "Gò Quao"},
    {"city": "Kiên Giang", "district": "Hà Tiên"},
    {"city": "Kiên Giang", "district": "Hòn Đất"},
    {"city": "Kiên Giang", "district": "Kiên Hải"},
    {"city": "Kiên Giang", "district": "Kiên Lương"},
    {"city": "Kiên Giang", "district": "Phú Quốc"},
    {"city": "Kiên Giang", "district": "Rạch Giá"},
    {"city": "Kiên Giang", "district": "Tân Hiệp"},
    {"city": "Kiên Giang", "district": "U Minh Thượng"},
    {"city": "Kiên Giang", "district": "Vĩnh Thuận"},
    {"city": "Kon Tum", "district": "Đắk Glei"},
    {"city": "Kon Tum", "district": "Đắk Hà"},
    {"city": "Kon Tum", "district": "Đắk Tô"},
    {"city": "Kon Tum", "district": "Ia H'Drai"},
    {"city": "Kon Tum", "district": "Kon Plông"},
    {"city": "Kon Tum", "district": "Kon Rẫy"},
    {"city": "Kon Tum", "district": "Kon Tum"},
    {"city": "Kon Tum", "district": "Ngọc Hồi"},
    {"city": "Kon Tum", "district": "Sa Thầy"},
    {"city": "Kon Tum", "district": "Tu Mơ Rông"},
    {"city": "Lai Châu", "district": "Lai Châu"},
    {"city": "Lai Châu", "district": "Mường Tè"},
    {"city": "Lai Châu", "district": "Nậm Nhùn"},
    {"city": "Lai Châu", "district": "Phong Thổ"},
    {"city": "Lai Châu", "district": "Sìn Hồ"},
    {"city": "Lai Châu", "district": "Tam Đường"},
    {"city": "Lai Châu", "district": "Tân Uyên"},
    {"city": "Lai Châu", "district": "Than Uyên"},
    {"city": "Lâm Đồng", "district": "Bảo Lâm"},
    {"city": "Lâm Đồng", "district": "Bảo Lộc"},
    {"city": "Lâm Đồng", "district": "Cát Tiên"},
    {"city": "Lâm Đồng", "district": "Đạ Huoai"},
    {"city": "Lâm Đồng", "district": "Đà Lạt"},
    {"city": "Lâm Đồng", "district": "Đam Rông"},
    {"city": "Lâm Đồng", "district": "Đạ Tẻh"},
    {"city": "Lâm Đồng", "district": "Di Linh"},
    {"city": "Lâm Đồng", "district": "Đơn Dương"},
    {"city": "Lâm Đồng", "district": "Đức Trọng"},
    {"city": "Lâm Đồng", "district": "Lạc Dương"},
    {"city": "Lâm Đồng", "district": "Lâm Hà"},
    {"city": "Lạng Sơn", "district": "Bắc Sơn"},
    {"city": "Lạng Sơn", "district": "Bình Gia"},
    {"city": "Lạng Sơn", "district": "Cao Lộc"},
    {"city": "Lạng Sơn", "district": "Chi Lăng"},
    {"city": "Lạng Sơn", "district": "Đình Lập"},
    {"city": "Lạng Sơn", "district": "Hữu Lũng"},
    {"city": "Lạng Sơn", "district": "Lạng Sơn"},
    {"city": "Lạng Sơn", "district": "Lộc Bình"},
    {"city": "Lạng Sơn", "district": "Tràng Định"},
    {"city": "Lạng Sơn", "district": "Văn Lãng"},
    {"city": "Lạng Sơn", "district": "Văn Quan"},
    {"city": "Lào Cai", "district": "Bắc Hà"},
    {"city": "Lào Cai", "district": "Bảo Thắng"},
    {"city": "Lào Cai", "district": "Bảo Yên"},
    {"city": "Lào Cai", "district": "Bát Xát"},
    {"city": "Lào Cai", "district": "Lào Cai"},
    {"city": "Lào Cai", "district": "Mường Khương"},
    {"city": "Lào Cai", "district": "Sa Pa"},
    {"city": "Lào Cai", "district": "Si Ma Cai"},
    {"city": "Lào Cai", "district": "Văn Bàn"},
    {"city": "Long An", "district": "Bến Lức"},
    {"city": "Long An", "district": "Cần Đước"},
    {"city": "Long An", "district": "Cần Giuộc"},
    {"city": "Long An", "district": "Châu Thành"},
    {"city": "Long An", "district": "Đức Hòa"},
    {"city": "Long An", "district": "Đức Huệ"},
    {"city": "Long An", "district": "Mộc Hóa"},
    {"city": "Long An", "district": "Tân An"},
    {"city": "Long An", "district": "Tân Hưng"},
    {"city": "Long An", "district": "Tân Thạnh"},
    {"city": "Long An", "district": "Tân Trụ"},
    {"city": "Long An", "district": "Thạnh Hóa"},
    {"city": "Long An", "district": "Thủ Thừa"},
    {"city": "Long An", "district": "Vĩnh Hưng"},
    {"city": "Nam Định", "district": "Giao Thủy"},
    {"city": "Nam Định", "district": "Hải Hậu"},
    {"city": "Nam Định", "district": "Mỹ Lộc"},
    {"city": "Nam Định", "district": "Nam Định"},
    {"city": "Nam Định", "district": "Nam Trực"},
    {"city": "Nam Định", "district": "Nghĩa Hưng"},
    {"city": "Nam Định", "district": "Trực Ninh"},
    {"city": "Nam Định", "district": "Vụ Bản"},
    {"city": "Nam Định", "district": "Xuân Trường"},
    {"city": "Nam Định", "district": "Ý Yên"},
    {"city": "Nghệ An", "district": "Anh Sơn"},
    {"city": "Nghệ An", "district": "Con Cuông"},
    {"city": "Nghệ An", "district": "Diễn Châu"},
    {"city": "Nghệ An", "district": "Đô Lương"},
    {"city": "Nghệ An", "district": "Hưng Nguyên"},
    {"city": "Nghệ An", "district": "Kỳ Sơn"},
    {"city": "Nghệ An", "district": "Nam Đàn"},
    {"city": "Nghệ An", "district": "Nghĩa Đàn"},
    {"city": "Nghệ An", "district": "Nghi Lộc"},
    {"city": "Nghệ An", "district": "Quế Phong"},
    {"city": "Nghệ An", "district": "Quỳ Châu"},
    {"city": "Nghệ An", "district": "Quỳ Hợp"},
    {"city": "Nghệ An", "district": "Quỳnh Lưu"},
    {"city": "Nghệ An", "district": "Tân Kỳ"},
    {"city": "Nghệ An", "district": "Thanh Chương"},
    {"city": "Nghệ An", "district": "Tương Dương"},
    {"city": "Nghệ An", "district": "Vinh"},
    {"city": "Nghệ An", "district": "Yên Thành"},
    {"city": "Ninh Bình", "district": "Gia Viễn"},
    {"city": "Ninh Bình", "district": "Hoa Lư"},
    {"city": "Ninh Bình", "district": "Kim Sơn"},
    {"city": "Ninh Bình", "district": "Nho Quan"},
    {"city": "Ninh Bình", "district": "Ninh Bình"},
    {"city": "Ninh Bình", "district": "Tam Điệp"},
    {"city": "Ninh Bình", "district": "Yên Khánh"},
    {"city": "Ninh Bình", "district": "Yên Mô"},
    {"city": "Ninh Thuận", "district": "Bác Ái"},
    {"city": "Ninh Thuận", "district": "Ninh Hải"},
    {"city": "Ninh Thuận", "district": "Ninh Phước"},
    {"city": "Ninh Thuận", "district": "Ninh Sơn"},
    {"city": "Ninh Thuận", "district": "Phan Rang - Tháp Chàm"},
    {"city": "Ninh Thuận", "district": "Thuận Bắc"},
    {"city": "Ninh Thuận", "district": "Thuận Nam"},
    {"city": "Phú Thọ", "district": "Cẩm Khê"},
    {"city": "Phú Thọ", "district": "Đoan Hùng"},
    {"city": "Phú Thọ", "district": "Hạ Hòa"},
    {"city": "Phú Thọ", "district": "Lâm Thao"},
    {"city": "Phú Thọ", "district": "Phù Ninh"},
    {"city": "Phú Thọ", "district": "Tam Nông"},
    {"city": "Phú Thọ", "district": "Tân Sơn"},
    {"city": "Phú Thọ", "district": "Thanh Ba"},
    {"city": "Phú Thọ", "district": "Thanh Sơn"},
    {"city": "Phú Thọ", "district": "Thanh Thủy"},
    {"city": "Phú Thọ", "district": "Việt Trì"},
    {"city": "Phú Thọ", "district": "Yên Lập"},
    {"city": "Phú Yên", "district": "Đông Hòa"},
    {"city": "Phú Yên", "district": "Đồng Xuân"},
    {"city": "Phú Yên", "district": "Phú Hòa"},
    {"city": "Phú Yên", "district": "Sông Hinh"},
    {"city": "Phú Yên", "district": "Sơn Hòa"},
    {"city": "Phú Yên", "district": "Tây Hòa"},
    {"city": "Phú Yên", "district": "Tuy An"},
    {"city": "Phú Yên", "district": "Tuy Hòa"},
    {"city": "Quảng Bình", "district": "Bố Trạch"},
    {"city": "Quảng Bình", "district": "Đồng Hới"},
    {"city": "Quảng Bình", "district": "Lệ Thủy"},
    {"city": "Quảng Bình", "district": "Minh Hóa"},
    {"city": "Quảng Bình", "district": "Quảng Ninh"},
    {"city": "Quảng Bình", "district": "Quảng Trạch"},
    {"city": "Quảng Bình", "district": "Tuyên Hóa"},
    {"city": "Quảng Nam", "district": "Bắc Trà My"},
    {"city": "Quảng Nam", "district": "Đại Lộc"},
    {"city": "Quảng Nam", "district": "Đông Giang"},
    {"city": "Quảng Nam", "district": "Duy Xuyên"},
    {"city": "Quảng Nam", "district": "Hiệp Đức"},
    {"city": "Quảng Nam", "district": "Hội An"},
    {"city": "Quảng Nam", "district": "Nam Giang"},
    {"city": "Quảng Nam", "district": "Nam Trà My"},
    {"city": "Quảng Nam", "district": "Nông Sơn"},
    {"city": "Quảng Nam", "district": "Núi Thành"},
    {"city": "Quảng Nam", "district": "Phú Ninh"},
    {"city": "Quảng Nam", "district": "Phước Sơn"},
    {"city": "Quảng Nam", "district": "Quế Sơn"},
    {"city": "Quảng Nam", "district": "Tam Kỳ"},
    {"city": "Quảng Nam", "district": "Tây Giang"},
    {"city": "Quảng Nam", "district": "Thăng Bình"},
    {"city": "Quảng Nam", "district": "Tiên Phước"},
    {"city": "Quảng Ngãi", "district": "Ba Tơ"},
    {"city": "Quảng Ngãi", "district": "Bình Sơn"},
    {"city": "Quảng Ngãi", "district": "Đức Phổ"},
    {"city": "Quảng Ngãi", "district": "Lý Sơn"},
    {"city": "Quảng Ngãi", "district": "Minh Long"},
    {"city": "Quảng Ngãi", "district": "Mộ Đức"},
    {"city": "Quảng Ngãi", "district": "Nghĩa Hành"},
    {"city": "Quảng Ngãi", "district": "Quảng Ngãi"},
    {"city": "Quảng Ngãi", "district": "Sơn Hà"},
    {"city": "Quảng Ngãi", "district": "Sơn Tây"},
    {"city": "Quảng Ngãi", "district": "Sơn Tịnh"},
    {"city": "Quảng Ngãi", "district": "Tây Trà"},
    {"city": "Quảng Ngãi", "district": "Trà Bồng"},
    {"city": "Quảng Ngãi", "district": "Tư Nghĩa"},
    {"city": "Quảng Ninh", "district": "Ba Chẽ"},
    {"city": "Quảng Ninh", "district": "Bình Liêu"},
    {"city": "Quảng Ninh", "district": "Cẩm Phả"},
    {"city": "Quảng Ninh", "district": "Cô Tô"},
    {"city": "Quảng Ninh", "district": "Đầm Hà"},
    {"city": "Quảng Ninh", "district": "Hải Hà"},
    {"city": "Quảng Ninh", "district": "Hạ Long"},
    {"city": "Quảng Ninh", "district": "Hoành Bồ"},
    {"city": "Quảng Ninh", "district": "Móng Cái"},
    {"city": "Quảng Ninh", "district": "Tiên Yên"},
    {"city": "Quảng Ninh", "district": "Uông Bí"},
    {"city": "Quảng Ninh", "district": "Vân Đồn"},
    {"city": "Quảng Trị", "district": "Cam Lộ"},
    {"city": "Quảng Trị", "district": "Cồn Cỏ"},
    {"city": "Quảng Trị", "district": "Đa Krông"},
    {"city": "Quảng Trị", "district": "Đông Hà"},
    {"city": "Quảng Trị", "district": "Gio Linh"},
    {"city": "Quảng Trị", "district": "Hải Lăng"},
    {"city": "Quảng Trị", "district": "Hướng Hóa"},
    {"city": "Quảng Trị", "district": "Triệu Phong"},
    {"city": "Quảng Trị", "district": "Vĩnh Linh"},
    {"city": "Sóc Trăng", "district": "Châu Thành"},
    {"city": "Sóc Trăng", "district": "Cù Lao Dung"},
    {"city": "Sóc Trăng", "district": "Kế Sách"},
    {"city": "Sóc Trăng", "district": "Long Phú"},
    {"city": "Sóc Trăng", "district": "Mỹ Tú"},
    {"city": "Sóc Trăng", "district": "Mỹ Xuyên"},
    {"city": "Sóc Trăng", "district": "Sóc Trăng"},
    {"city": "Sóc Trăng", "district": "Thạnh Trị"},
    {"city": "Sóc Trăng", "district": "Trần Đề"},
    {"city": "Sơn La", "district": "Bắc Yên"},
    {"city": "Sơn La", "district": "Mai Sơn"},
    {"city": "Sơn La", "district": "Mộc Châu"},
    {"city": "Sơn La", "district": "Mường La"},
    {"city": "Sơn La", "district": "Phù Yên"},
    {"city": "Sơn La", "district": "Quỳnh Nhai"},
    {"city": "Sơn La", "district": "Sông Mã"},
    {"city": "Sơn La", "district": "Sơn La"},
    {"city": "Sơn La", "district": "Sốp Cộp"},
    {"city": "Sơn La", "district": "Thuận Châu"},
    {"city": "Sơn La", "district": "Vân Hồ"},
    {"city": "Sơn La", "district": "Yên Châu"},
    {"city": "Tây Ninh", "district": "Bến Cầu"},
    {"city": "Tây Ninh", "district": "Châu Thành"},
    {"city": "Tây Ninh", "district": "Dương Minh Châu"},
    {"city": "Tây Ninh", "district": "Gò Dầu"},
    {"city": "Tây Ninh", "district": "Hòa Thành"},
    {"city": "Tây Ninh", "district": "Tân Biên"},
    {"city": "Tây Ninh", "district": "Tân Châu"},
    {"city": "Tây Ninh", "district": "Tây Ninh"},
    {"city": "Tây Ninh", "district": "Trảng Bàng"},
    {"city": "Thái Bình", "district": "Đông Hưng"},
    {"city": "Thái Bình", "district": "Hưng Hà"},
    {"city": "Thái Bình", "district": "Kiến Xương"},
    {"city": "Thái Bình", "district": "Quỳnh Phụ"},
    {"city": "Thái Bình", "district": "Thái Bình"},
    {"city": "Thái Bình", "district": "Thái Thụy"},
    {"city": "Thái Bình", "district": "Tiền Hải"},
    {"city": "Thái Bình", "district": "Vũ Thư"},
    {"city": "Thái Nguyên", "district": "Đại Từ"},
    {"city": "Thái Nguyên", "district": "Định Hóa"},
    {"city": "Thái Nguyên", "district": "Đồng Hỷ"},
    {"city": "Thái Nguyên", "district": "Phú Bình"},
    {"city": "Thái Nguyên", "district": "Phú Lương"},
    {"city": "Thái Nguyên", "district": "Sông Công"},
    {"city": "Thái Nguyên", "district": "Thái Nguyên"},
    {"city": "Thái Nguyên", "district": "Võ Nhai"},
    {"city": "Thanh Hóa", "district": "Bá Thước"},
    {"city": "Thanh Hóa", "district": "Cẩm Thủy"},
    {"city": "Thanh Hóa", "district": "Đông Sơn"},
    {"city": "Thanh Hóa", "district": "Hà Trung"},
    {"city": "Thanh Hóa", "district": "Hậu Lộc"},
    {"city": "Thanh Hóa", "district": "Hoằng Hóa"},
    {"city": "Thanh Hóa", "district": "Lang Chánh"},
    {"city": "Thanh Hóa", "district": "Mường Lát"},
    {"city": "Thanh Hóa", "district": "Nga Sơn"},
    {"city": "Thanh Hóa", "district": "Ngọc Lặc"},
    {"city": "Thanh Hóa", "district": "Như Thanh"},
    {"city": "Thanh Hóa", "district": "Như Xuân"},
    {"city": "Thanh Hóa", "district": "Nông Cống"},
    {"city": "Thanh Hóa", "district": "Quảng Xương"},
    {"city": "Thanh Hóa", "district": "Quan Hóa"},
    {"city": "Thanh Hóa", "district": "Quan Sơn"},
    {"city": "Thanh Hóa", "district": "Sầm Sơn"},
    {"city": "Thanh Hóa", "district": "Thạch Thành"},
    {"city": "Thanh Hóa", "district": "Thanh Hóa"},
    {"city": "Thanh Hóa", "district": "Thiệu Hóa"},
    {"city": "Thanh Hóa", "district": "Thọ Xuân"},
    {"city": "Thanh Hóa", "district": "Thường Xuân"},
    {"city": "Thanh Hóa", "district": "Tĩnh Gia"},
    {"city": "Thanh Hóa", "district": "Triệu Sơn"},
    {"city": "Thanh Hóa", "district": "Vĩnh Lộc"},
    {"city": "Thanh Hóa", "district": "Yên Định"},
    {"city": "Thừa Thiên - Huế", "district": "A Lưới"},
    {"city": "Thừa Thiên - Huế", "district": "Huế"},
    {"city": "Thừa Thiên - Huế", "district": "Nam Đông"},
    {"city": "Thừa Thiên - Huế", "district": "Phong Điền"},
    {"city": "Thừa Thiên - Huế", "district": "Phú Lộc"},
    {"city": "Thừa Thiên - Huế", "district": "Phú Vang"},
    {"city": "Thừa Thiên - Huế", "district": "Quảng Điền"},
    {"city": "Tiền Giang", "district": "Cái Bè"},
    {"city": "Tiền Giang", "district": "Cai Lậy"},
    {"city": "Tiền Giang", "district": "Châu Thành"},
    {"city": "Tiền Giang", "district": "Chợ Gạo"},
    {"city": "Tiền Giang", "district": "Gò Công Đông"},
    {"city": "Tiền Giang", "district": "Gò Công Tây"},
    {"city": "Tiền Giang", "district": "Mỹ Tho"},
    {"city": "Tiền Giang", "district": "Tân Phú Đông"},
    {"city": "Tiền Giang", "district": "Tân Phước"},
    {"city": "Trà Vinh", "district": "Càng Long"},
    {"city": "Trà Vinh", "district": "Cầu Kè"},
    {"city": "Trà Vinh", "district": "Cầu Ngang"},
    {"city": "Trà Vinh", "district": "Châu Thành"},
    {"city": "Trà Vinh", "district": "Duyên Hải"},
    {"city": "Trà Vinh", "district": "Tiểu Cần"},
    {"city": "Trà Vinh", "district": "Trà Cú"},
    {"city": "Trà Vinh", "district": "Trà Vinh"},
    {"city": "Tuyên Quang", "district": "Chiêm Hóa"},
    {"city": "Tuyên Quang", "district": "Hàm Yên"},
    {"city": "Tuyên Quang", "district": "Lâm Bình"},
    {"city": "Tuyên Quang", "district": "Nà Hang"},
    {"city": "Tuyên Quang", "district": "Sơn Dương"},
    {"city": "Tuyên Quang", "district": "Tuyên Quang"},
    {"city": "Tuyên Quang", "district": "Yên Sơn"},
    {"city": "Vĩnh Long", "district": "Bình Tân"},
    {"city": "Vĩnh Long", "district": "Long Hồ"},
    {"city": "Vĩnh Long", "district": "Mang Thít"},
    {"city": "Vĩnh Long", "district": "Tam Bình"},
    {"city": "Vĩnh Long", "district": "Trà Ôn"},
    {"city": "Vĩnh Long", "district": "Vĩnh Long"},
    {"city": "Vĩnh Long", "district": "Vũng Liêm"},
    {"city": "Vĩnh Phúc", "district": "Bình Xuyên"},
    {"city": "Vĩnh Phúc", "district": "Lập Thạch"},
    {"city": "Vĩnh Phúc", "district": "Phúc Yên"},
    {"city": "Vĩnh Phúc", "district": "Sông Lô"},
    {"city": "Vĩnh Phúc", "district": "Tam Đảo"},
    {"city": "Vĩnh Phúc", "district": "Tam Dương"},
    {"city": "Vĩnh Phúc", "district": "Vĩnh Tường"},
    {"city": "Vĩnh Phúc", "district": "Vĩnh Yên"},
    {"city": "Vĩnh Phúc", "district": "Yên Lạc"},
    {"city": "Yên Bái", "district": "Lục Yên"},
    {"city": "Yên Bái", "district": "Mù Cang Chải"},
    {"city": "Yên Bái", "district": "Trạm Tấu"},
    {"city": "Yên Bái", "district": "Trấn Yên"},
    {"city": "Yên Bái", "district": "Văn Chấn"},
    {"city": "Yên Bái", "district": "Văn Yên"},
    {"city": "Yên Bái", "district": "Yên Bái"},
    {"city": "Yên Bái", "district": "Yên Bình"},
]

module.exports = districts